# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(default='user', max_length=25),
        ),
    ]
